CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME (username), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4;
DROP TABLE t_log;

-- DROP FOREIGN KEY
ALTER TABLE scores DROP FOREIGN KEY `fk_scores_4`;
ALTER TABLE scores DROP FOREIGN KEY `scores_ibfk_1`;
ALTER TABLE scores DROP FOREIGN KEY `scores_ibfk_2`;
ALTER TABLE scores DROP FOREIGN KEY `scores_ibfk_3`;
ALTER TABLE players DROP FOREIGN KEY `players_ibfk_1`;
ALTER TABLE strats DROP FOREIGN KEY `fk_strats`;
ALTER TABLE strats_cars DROP FOREIGN KEY `fk_strats_cars_1`;
ALTER TABLE strats_cars DROP FOREIGN KEY `fk_strats_cars_2`;
ALTER TABLE stars DROP FOREIGN KEY `stars_ibfk_1`;


-- DROP INDEX
DROP INDEX un_zones ON zones;
DROP INDEX in_countries ON countries;
DROP INDEX un_countries_1 ON countries;
DROP INDEX un_countries_2 ON countries;
DROP INDEX un_countries_3 ON countries;
DROP INDEX player ON scores;
DROP INDEX zone ON scores;
DROP INDEX fk_scores_4 ON scores;
DROP INDEX car ON scores;
DROP INDEX country ON players;
DROP INDEX in_players ON players;
DROP INDEX un_players ON players;
DROP INDEX un_players_2 ON players;
DROP INDEX un_cars ON cars;
DROP INDEX un_zones ON strats;
DROP INDEX fk_strats_cars_2 ON strats_cars;
DROP INDEX un_zones ON stars;


-- DROP PRIMARY KEY
ALTER TABLE strats_cars DROP PRIMARY KEY;


-- CHANGE PRIMARY KEY
ALTER TABLE cars CHANGE id id INT AUTO_INCREMENT NOT NULL;
ALTER TABLE scores CHANGE id id INT AUTO_INCREMENT NOT NULL;
ALTER TABLE news CHANGE id id INT AUTO_INCREMENT NOT NULL;
ALTER TABLE players CHANGE id id INT AUTO_INCREMENT NOT NULL;
ALTER TABLE countries CHANGE id id INT AUTO_INCREMENT NOT NULL;
ALTER TABLE strats CHANGE id id INT AUTO_INCREMENT NOT NULL;
ALTER TABLE stars CHANGE id id INT AUTO_INCREMENT NOT NULL;
ALTER TABLE zones CHANGE id id INT AUTO_INCREMENT NOT NULL;

-- RENAME FOREIGN KEY
ALTER TABLE scores CHANGE player player_id INT NOT NULL;
ALTER TABLE scores CHANGE zone zone_id INT NOT NULL;
ALTER TABLE scores CHANGE car car_id INT DEFAULT NULL;
ALTER TABLE scores CHANGE strat strat_id INT DEFAULT NULL;
ALTER TABLE players CHANGE country country_id INT NOT NULL;
ALTER TABLE strats CHANGE zone zone_id INT NOT NULL;
ALTER TABLE strats_cars CHANGE strat strat_id INT NOT NULL;
ALTER TABLE strats_cars CHANGE car car_id INT NOT NULL;
ALTER TABLE stars CHANGE zone zone_id INT NOT NULL;

-- ADD PRIMARY KEY
ALTER TABLE strats_cars ADD PRIMARY KEY (strat_id, car_id);


-- ADD FOREIGN KEY
ALTER TABLE scores ADD CONSTRAINT FK_750375E99E6F5DF FOREIGN KEY (player_id) REFERENCES players (id);
ALTER TABLE scores ADD CONSTRAINT FK_750375E9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zones (id);
ALTER TABLE scores ADD CONSTRAINT FK_750375EC3C6F69F FOREIGN KEY (car_id) REFERENCES cars (id);
ALTER TABLE scores ADD CONSTRAINT FK_750375EC03F64FC FOREIGN KEY (strat_id) REFERENCES strats (id);
ALTER TABLE strats ADD CONSTRAINT FK_3A5ACDB79F2C3FAB FOREIGN KEY (zone_id) REFERENCES zones (id);
ALTER TABLE players ADD CONSTRAINT FK_264E43A6F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id);
ALTER TABLE strats_cars ADD CONSTRAINT FK_AAA0FACFC03F64FC FOREIGN KEY (strat_id) REFERENCES strats (id) ON DELETE CASCADE;
ALTER TABLE strats_cars ADD CONSTRAINT FK_AAA0FACFC3C6F69F FOREIGN KEY (car_id) REFERENCES cars (id) ON DELETE CASCADE;
ALTER TABLE stars ADD CONSTRAINT FK_11DC02C9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zones (id);


-- (X) ADD INDEX
ALTER TABLE countries ADD INDEX idx_country_abr (abr);
ALTER TABLE countries ADD INDEX idx_country_iso (iso);
CREATE INDEX IDX_750375E99E6F5DF ON scores (player_id);
CREATE INDEX IDX_750375E9F2C3FAB ON scores (zone_id);
CREATE INDEX IDX_750375EC3C6F69F ON scores (car_id);
CREATE INDEX IDX_750375EC03F64FC ON scores (strat_id);
CREATE INDEX idx_player_zone ON scores (player_id, zone_id);
CREATE INDEX idx_zone_score ON scores (zone_id, score);
CREATE INDEX IDX_264E43A6F92F3E70 ON players (country_id);
CREATE INDEX IDX_3A5ACDB79F2C3FAB ON strats (zone_id);
CREATE INDEX IDX_AAA0FACFC03F64FC ON strats_cars (strat_id);
CREATE INDEX IDX_AAA0FACFC3C6F69F ON strats_cars (car_id);
CREATE INDEX IDX_11DC02C9F2C3FAB ON stars (zone_id);
CREATE UNIQUE INDEX UNIQ_ZONE_NBSTARS ON stars (zone_id, nb_stars);


-- RENAME COMMON COLUMN
ALTER TABLE `zones` CHANGE `bestvids_channel` `best_vids_channel` VARCHAR(255) NOT NULL;
ALTER TABLE strats CHANGE name name VARCHAR(255) NOT NULL;
ALTER TABLE strats CHANGE description description LONGTEXT NOT NULL;
ALTER TABLE strats CHANGE runaway runaway TINYINT DEFAULT NULL;
ALTER TABLE strats CHANGE hz50 hz50 TINYINT DEFAULT NULL;
ALTER TABLE strats CHANGE hz60 hz60 TINYINT DEFAULT NULL;
ALTER TABLE strats CHANGE gc gc TINYINT DEFAULT NULL;
ALTER TABLE strats CHANGE xbox xbox TINYINT DEFAULT NULL;
ALTER TABLE strats CHANGE ps2 ps2 TINYINT DEFAULT NULL;
ALTER TABLE strats CHANGE best_damage best_damage BIGINT UNSIGNED NOT NULL;
ALTER TABLE strats CHANGE best_multi best_multi BIGINT UNSIGNED NOT NULL;
ALTER TABLE strats CHANGE best_total best_total BIGINT UNSIGNED NOT NULL;
ALTER TABLE strats CHANGE best_damage best_damage BIGINT UNSIGNED NOT NULL;
ALTER TABLE strats CHANGE best_multi best_multi BIGINT UNSIGNED NOT NULL;
ALTER TABLE strats CHANGE best_total best_total BIGINT UNSIGNED NOT NULL;
ALTER TABLE players CHANGE name name VARCHAR(255) NOT NULL, CHANGE name_url name_url VARCHAR(255) NOT NULL, CHANGE notes notes LONGTEXT DEFAULT NULL, CHANGE total total BIGINT UNSIGNED DEFAULT NULL, CHANGE total_rank total_rank INT DEFAULT NULL, CHANGE avg_pos avg_pos NUMERIC(5, 3) DEFAULT NULL, CHANGE avg_pos_rank avg_pos_rank INT DEFAULT NULL, CHANGE avg_percent avg_percent NUMERIC(5, 2) DEFAULT NULL, CHANGE avg_percent_rank avg_percent_rank INT DEFAULT NULL, CHANGE avg_stars avg_stars NUMERIC(3, 1) DEFAULT NULL, CHANGE avg_stars_rank avg_stars_rank INT DEFAULT NULL, CHANGE xbl_total xbl_total TINYINT DEFAULT NULL;
ALTER TABLE scores CHANGE proof_type proof_type VARCHAR(20) DEFAULT NULL, CHANGE platform platform VARCHAR(10) DEFAULT NULL, CHANGE version version VARCHAR(10) DEFAULT NULL, CHANGE freq freq VARCHAR(10) DEFAULT NULL, CHANGE emulator emulator TINYINT DEFAULT 0 NOT NULL, CHANGE glitch glitch VARCHAR(10) DEFAULT NULL, CHANGE score score BIGINT UNSIGNED NOT NULL, CHANGE multi multi BIGINT UNSIGNED DEFAULT NULL, CHANGE damage damage BIGINT UNSIGNED DEFAULT NULL, CHANGE percent_wr percent_wr NUMERIC(5, 2) DEFAULT NULL, CHANGE stars stars INT DEFAULT NULL;
ALTER TABLE stars CHANGE score score BIGINT UNSIGNED NOT NULL;
ALTER TABLE cars CHANGE name name VARCHAR(255) NOT NULL;
ALTER TABLE countries CHANGE name name VARCHAR(255) NOT NULL, CHANGE name_url name_url VARCHAR(255) NOT NULL;
ALTER TABLE news CHANGE content content LONGTEXT NOT NULL;
ALTER TABLE strats CHANGE best_damage best_damage BIGINT UNSIGNED NOT NULL, CHANGE best_multi best_multi BIGINT UNSIGNED NOT NULL, CHANGE best_total best_total BIGINT UNSIGNED NOT NULL;
ALTER TABLE zones CHANGE name name VARCHAR(255) NOT NULL, CHANGE ps2 ps2 TINYINT DEFAULT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE best_damage best_damage BIGINT UNSIGNED NOT NULL, CHANGE best_multi best_multi BIGINT UNSIGNED NOT NULL, CHANGE best_total best_total BIGINT UNSIGNED NOT NULL, CHANGE glitch glitch VARCHAR(255) DEFAULT NULL, CHANGE dmg_wr_known dmg_wr_known TINYINT DEFAULT NULL;


